version: "3.2"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: local-zookeeper
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka:latest
    container_name: local-kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT